=== slub/librml/librml-py/librml/schemas/librml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://librml.org/schema"
    xmlns:libRML="http://librml.org/schema"
    attributeFormDefault="unqualified"
    elementFormDefault="qualified"
    version="0.5.0">
    <xs:element name="libRML" type="libRML:libRMLType" />

    <!-- libRMLType - Container for all -->
    <xs:complexType name="libRMLType">
        <!-- Contains only 1 subelement and a string 'version' -->
        <xs:sequence>
            <xs:element type="libRML:ItemType" name="item" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="version" />
    </xs:complexType>

    <!-- itemType - has many actions and some attributes -->
    <xs:complexType name="ItemType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element type="libRML:ActionType" name="action" />
        </xs:sequence>
        <xs:attribute type="xs:NMTOKEN" name="id" />
        <xs:attribute type="xs:anyURI" name="tenant" />
        <xs:attribute type="xs:boolean" name="mention" />
        <xs:attribute type="xs:boolean" name="sharealike" />
        <xs:attribute type="xs:boolean" name="commercialuse" />
        <xs:attribute type="xs:boolean" name="copyright" />
        <xs:attribute type="xs:string" name="template" />
        <xs:attribute type="xs:anyURI" name="usageguide" />
    </xs:complexType>

    <!-- ActionType - has many restrictions and some attributes -->
    <xs:complexType name="ActionType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element type="libRML:RestrictionType" name="restriction" />
        </xs:sequence>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:NMTOKEN">
                    <xs:enumeration value="archive" />
                    <xs:enumeration value="displaymetadata" />
                    <xs:enumeration value="distribute" />
                    <xs:enumeration value="download" />
                    <xs:enumeration value="index" />
                    <xs:enumeration value="lend" />
                    <xs:enumeration value="modify" />
                    <xs:enumeration value="move" />
                    <xs:enumeration value="print" />
                    <xs:enumeration value="publish" />
                    <xs:enumeration value="read" />
                    <xs:enumeration value="reproduce" />
                    <xs:enumeration value="reuse" />
                    <xs:enumeration value="run" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:boolean" name="permission" use="required" />
    </xs:complexType>

    <!-- RestrictionType -->
    <xs:complexType name="RestrictionType">
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:NMTOKEN">
                    <xs:enumeration value="age" />
                    <xs:enumeration value="agreement" />
                    <xs:enumeration value="concurrent" />
                    <xs:enumeration value="count" />
                    <xs:enumeration value="date" />
                    <xs:enumeration value="duration" />
                    <xs:enumeration value="group" />
                    <xs:enumeration value="location" />
                    <xs:enumeration value="parts" />
                    <xs:enumeration value="quality" />
                    <xs:enumeration value="watermark" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attributeGroup ref="libRML:ageattr" />
        <xs:attributeGroup ref="libRML:datattr" />
        <xs:attributeGroup ref="libRML:locattr" />
        <xs:attributeGroup ref="libRML:qltattr" />
        <xs:attribute type="xs:positiveInteger" name="count" />
        <xs:attribute type="xs:NMTOKENS" name="groups" />
        <xs:attribute type="xs:positiveInteger" name="maxduration" />
        <xs:attribute type="xs:nonNegativeInteger" name="percentage" />
        <xs:attribute type="xs:boolean" name="required" />
        <xs:attribute type="xs:positiveInteger" name="sessions" />
        <xs:attribute type="xs:string" name="watermarkvalue" />
    </xs:complexType>
    <xs:attributeGroup name="ageattr">
        <xs:attribute type="xs:positiveInteger" name="minage" />
        <xs:attribute type="xs:positiveInteger" name="maxage" />
    </xs:attributeGroup>
    <xs:attributeGroup name="datattr">
        <xs:attribute type="xs:date" name="fromdate" />
        <xs:attribute type="xs:date" name="todate" />
    </xs:attributeGroup>
    <xs:attributeGroup name="locattr">
        <xs:attribute type="xs:Name" name="inside" />
        <xs:attribute type="xs:Name" name="outside" />
        <xs:attribute name="subnet">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <!-- Regex for IPV4 incl. CDIR -->
                    <xs:pattern
                        value="((1?\d?\d|2[0-4]\d|25[0-5])\.){3}(1?\d?\d|2[0-4]\d|25[0-5])/(3[0-2]|[12]?\d)" />
                    <!-- Regex for IPv6 -->
                    <xs:pattern
                        value="(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}(:[0-9a-fA-F]{1,4}){1,6}|:((:[0-9a-fA-F]{1,4}){1,7}|:))/(12[0-8]|1[01][0-9]|[1-9][0-9]|[0-9])"
                    />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    <xs:attributeGroup name="qltattr">
        <xs:attribute type="xs:positiveInteger" name="maxbitrate" />
        <xs:attribute type="xs:positiveInteger" name="maxdimension" />
        <xs:attribute type="xs:positiveInteger" name="maxresolution" />
    </xs:attributeGroup>
</xs:schema>

=== slub/librml/examples/klemperer.xml
<libRML:libRML xmlns:libRML="http://librml.org/schema" xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
      xsi:schemaLocation="http://librml.org/schema http://librml.org/schema/librml.xsd">
    <libRML:item id="klemperer-na-vk-tb-1.0"
        tenant="https://www.slub-dresden.de/"
        usageguide="https://nutzungshinweis.slub-dresden.de/na-vk-tb/1-0"
        copyright="true">
        <libRML:action type="displaymetadata" permission="true">
            <libRML:restriction type="mets" metssection="amdSec | dmdSec | structMap" />
        </libRML:action>
        <libRML:action type="download" permission="false">
        </libRML:action>
        <libRML:action type="index" permission="true">
            <libRML:restriction type="mets" metssection="dmdSec" />
        </libRML:action>
        <libRML:action type="publish" permission="true">
            <libRML:restriction type="interface" OAI-PMH="internal" />
        </libRML:action>
        <libRML:action type="read" permission="true">
            <libRML:restriction type="agreement" required="true" />
            <libRML:restriction type="concurrent" sessions="1" />
            <libRML:restriction type="group" groups="Arbeitsplatz Sondersammlungslesesaal SLUB" />
            <libRML:restriction type="mets" metsfilegroup="DEFAULT | FULLTEXT | THUMBS" />
        </libRML:action>
    </libRML:item>
</libRML:libRML>
